apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-demo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: app-demo
  type: LoadBalancer
